version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=sqlite3.db
      - DB_USER=
      - DB_PASSWORD=
      - DB_PORT=
  db:
    image: "sqlite:latest"
    volumes:
      - ./data:/data/db
    environment:
      - SQLITE_DATABASE=sqlite3.db
